---
# Default variables for the mysql role
mysql_enabled: true
mysql_service_name: "{{ mysql_service_name_map[ansible_os_family] }}"
mysql_service_state: started
mysql_service_enabled: true
# Root password should be defined via vault or host variables
mysql_root_password: ""
mysql_user: mysql
mysql_group: mysql
mysql_directories: []
mysql_packages:
  Debian:
    - mysql-server
    - mysql-client
    - python3-pymysql
  RedHat:
    - mariadb-server
    - mariadb
    - python3-PyMySQL
mysql_config_files: []
mysql_config_test_command: 'mysqld --help >/dev/null'
mysql_replication_user: replication
# Replication password should be provided via host vars or vault when replication is enabled
mysql_replication_password: ""
powerdns_db_name: powerdns
powerdns_db_user: powerdns
powerdns_db_password: ""
powerdns_db_host: localhost
powerdns_db_port: 3306
