version: '3.9'
services:
  audit-agent:
    build: .
    environment:
      - AGENT_API_KEY=${AGENT_API_KEY}
    volumes:
      - .:/app
    command: uvicorn api.server:app --host 0.0.0.0 --port 8000
