---
# Example inventory for PowerDNS Operations Collection
# Copy this file and customize for your environment

all:
  children:
    powerdns_primary:
      hosts:
        dns1.example.com:
          ansible_host: 192.168.1.10
          server_role: primary

    powerdns_secondary:
      hosts:
        dns2.example.com:
          ansible_host: 192.168.1.11
          server_role: secondary

    powerdns_recursor:
      hosts:
        recursor1.example.com:
          ansible_host: 192.168.1.12
          server_role: recursor

    haproxy_servers:
      hosts:
        lb1.example.com:
          ansible_host: 192.168.1.13
          server_role: loadbalancer

    mysql_servers:
      hosts:
        db1.example.com:
          ansible_host: 192.168.1.14
        db2.example.com:
          ansible_host: 192.168.1.15

  vars:
    # Common variables
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa

    # DNS configuration
    primary_domains:
      - example.com
      - internal.local

    # Network settings
    dns_network: "192.168.1.0/24"
    management_network: "192.168.1.0/24"
