---
# PowerDNS Infrastructure Inventory
# Anonymized for public release

all:
  children:
    powerdns_primary:
      hosts:
        ns1.example.com:
          ansible_host: 192.168.1.10
          server_role: primary
          powerdns_api_enabled: true
    
    powerdns_secondary:
      hosts:
        ns2.example.com:
          ansible_host: 192.168.1.11
          server_role: secondary
          powerdns_api_enabled: true
    
    powerdns_recursor:
      hosts:
        recursor1.example.com:
          ansible_host: 192.168.1.20
        recursor2.example.com:
          ansible_host: 192.168.1.21
    
    haproxy_servers:
      hosts:
        lb1.example.com:
          ansible_host: 192.168.1.30
        lb2.example.com:
          ansible_host: 192.168.1.31
    
    mysql_cluster:
      hosts:
        db1.example.com:
          ansible_host: 192.168.1.40
          mysql_server_id: 1
        db2.example.com:
          ansible_host: 192.168.1.41
          mysql_server_id: 2

  vars:
    # Global configuration
    ansible_user: ansible
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
    # DNS Configuration
    primary_domains:
      - "example.com"
      - "internal.local"
      - "lab.local"
    
    # Network configuration
    dns_network: "192.168.1.0/24"
    
    # Backup configuration
    backup_enabled: true
    backup_schedule: "0 2 * * *"
    backup_retention_days: 30
    
    # Monitoring
    monitoring_enabled: true
    prometheus_enabled: false
    
    # Security
    firewall_enabled: true
    security_hardening_enabled: true
