- name: Install AIDE
  ansible.builtin.package:
    name: aide
    state: present
  tags:
  - security
- name: Check if AIDE database exists
  ansible.builtin.stat:
    path: /var/lib/aide/aide.db
  register: aide_db_exists
  tags:
  - security
- name: Create AIDE configuration
  ansible.builtin.template:
    src: aide.conf.j2
    dest: /etc/aide/aide.conf
    owner: root
    group: root
    mode: '0600'
    backup: true
  notify: rebuild aide database
  tags:
  - security
- name: Initialize AIDE database (first time)
  ansible.builtin.command: aide --init
  when: not aide_db_exists.stat.exists
  register: aide_init
  changed_when: aide_init.rc == 0
  tags:
  - security
- name: Move new AIDE database to active location
  ansible.builtin.command: mv /var/lib/aide/aide.db.new /var/lib/aide/aide.db
  when: not aide_db_exists.stat.exists and aide_init.rc == 0
  tags:
  - security
- name: Create AIDE check script
  ansible.builtin.template:
    src: aide-check.sh.j2
    dest: /usr/local/bin/aide-check.sh
    owner: root
    group: root
    mode: '0755'
  tags:
  - security
- name: Create AIDE update script
  ansible.builtin.template:
    src: aide-update.sh.j2
    dest: /usr/local/bin/aide-update.sh
    owner: root
    group: root
    mode: '0755'
  tags:
  - security
- name: Schedule daily AIDE checks
  ansible.builtin.cron:
    name: AIDE integrity check
    cron_file: aide-check
    user: root
    minute: '0'
    hour: '3'
    job: /usr/local/bin/aide-check.sh
    state: present
  tags:
  - security
- name: Schedule weekly AIDE database updates
  ansible.builtin.cron:
    name: AIDE database update
    cron_file: aide-update
    user: root
    minute: '0'
    hour: '4'
    weekday: '0'
    job: /usr/local/bin/aide-update.sh
    state: present
  tags:
  - security
- name: Create AIDE log directory
  ansible.builtin.file:
    path: /var/log/aide
    state: directory
    owner: root
    group: root
    mode: '0750'
  tags:
  - security
- name: Configure AIDE log rotation
  ansible.builtin.template:
    src: aide-logrotate.j2
    dest: /etc/logrotate.d/aide
    owner: root
    group: root
    mode: '0644'
  tags:
  - security
- name: Set proper permissions on AIDE files
  ansible.builtin.file:
    path: '{{ item }}'
    owner: root
    group: root
    mode: '0600'
  loop:
  - /var/lib/aide/aide.db
  - /etc/aide/aide.conf
  ignore_errors: true
  tags:
  - security
- name: Display AIDE setup status
  ansible.builtin.debug:
    msg:
    - AIDE (file integrity monitoring) configured
    - 'Database location: /var/lib/aide/aide.db'
    - 'Configuration: /etc/aide/aide.conf'
    - 'Daily checks: 03:00 AM'
    - 'Weekly updates: Sunday 04:00 AM'
    - 'Logs: /var/log/aide/'
  tags:
  - security
