---
# Service management tasks for security

- name: Enable and start security service
  ansible.builtin.systemd:
    name: "{{ security_service_name | default('security') }}"
    state: "{{ security_service_state | default('started') }}"
    enabled: "{{ security_service_enabled | default(true) }}"
    daemon_reload: true
  tags:
    - security
    - service

- name: Verify security service is running
  ansible.builtin.systemd:
    name: "{{ security_service_name | default('security') }}"
  register: security_service_status
  tags:
    - security
    - service
    - verify

- name: Display security service status
  ansible.builtin.debug:
    msg: "security service is {{ security_service_status.status.ActiveState | default('unknown') }}"
  tags:
    - security
    - service
    - verify
