---
# Installation tasks for clean_install

- name: Update package cache
  ansible.builtin.package:
    update_cache: true
  when: ansible_os_family in ['Debian', 'RedHat']
  tags:
    - clean_install
    - install

- name: Install clean_install packages
  ansible.builtin.package:
    name: "{{ clean_install_packages[ansible_os_family] | default([]) }}"
    state: present
  when: clean_install_packages is defined
  tags:
    - clean_install
    - install

- name: Create clean_install directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ clean_install_user | default('root') }}"
    group: "{{ clean_install_group | default('root') }}"
    mode: '0755'
  loop: "{{ clean_install_directories | default([]) }}"
  tags:
    - clean_install
    - install
