---
# Default variables for the haproxy role
haproxy_enabled: true
haproxy_service_name: haproxy
haproxy_service_state: started
haproxy_service_enabled: true

haproxy_user: haproxy
haproxy_group: haproxy

haproxy_config_dir: /etc/haproxy
haproxy_config_file: /etc/haproxy/haproxy.cfg
haproxy_log_dir: /var/log/haproxy
haproxy_admin_socket: /run/haproxy/admin.sock

haproxy_frontend_port: 53
haproxy_stats_enabled: true
haproxy_stats_port: 8404
haproxy_stats_user: admin
# Password for the statistics endpoint. Should be set via Ansible Vault.
haproxy_stats_password: ""
haproxy_stats_uri: "/stats"

haproxy_max_connections: 2000
haproxy_timeout_connect: 5s
haproxy_timeout_client: 50s
haproxy_timeout_server: 50s
haproxy_ssl_enabled: false
haproxy_ssl_cert: /etc/ssl/certs/haproxy.pem

haproxy_firewall_enabled: true

# Additional service endpoints
haproxy_dns_port: 53
haproxy_api_enabled: true
haproxy_api_port: 8081
haproxy_mysql_enabled: true
haproxy_mysql_port: 3306
haproxy_recursor_enabled: false
haproxy_recursor_port: 5353
haproxy_health_port: 8080

# Monitoring and management
haproxy_monitor_user: haproxy_monitor
# Monitoring password should be stored in Ansible Vault
haproxy_monitor_password: ""
haproxy_mysql_monitoring: true

# Directories created during installation
haproxy_directories:
  - /etc/haproxy
  - /var/lib/haproxy
  - /var/log/haproxy
