---
# Default variables for the keepalived role
keepalived_enabled: true
keepalived_service_name: keepalived
keepalived_service_state: started
keepalived_service_enabled: true

keepalived_router_id: 51
keepalived_interface: "{{ ansible_default_ipv4.interface | default('eth0') }}"
keepalived_virtual_ipaddress:
  - 192.168.1.100
keepalived_priority: 100
keepalived_vrrp_auth_type: PASS
keepalived_vrrp_auth_password: changeme
keepalived_script: /usr/local/bin/check_service.sh
keepalived_notification_email: root@localhost
keepalived_check_interval: 2
