---
# Configuration tasks for powerdns

- name: Generate powerdns configuration files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
    backup: true
  loop: "{{ powerdns_config_files | default([]) }}"
  notify: "restart powerdns"
  tags:
    - powerdns
    - configure

- name: Validate powerdns configuration
  ansible.builtin.command: "{{ powerdns_config_test_command | default('echo Configuration validation not implemented') }}"
  register: powerdns_config_test
  changed_when: false
  failed_when: false
  tags:
    - powerdns
    - configure
    - validate
