---
# Configuration tasks for monitoring

- name: Generate monitoring configuration files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
    backup: true
  loop: "{{ monitoring_config_files | default([]) }}"
  notify: "restart monitoring"
  tags:
    - monitoring
    - configure

- name: Validate monitoring configuration
  ansible.builtin.command: "{{ monitoring_config_test_command | default('echo Configuration validation not implemented') }}"
  register: monitoring_config_test
  changed_when: false
  failed_when: false
  tags:
    - monitoring
    - configure
    - validate
