---
# Installation tasks for monitoring

- name: Update package cache
  ansible.builtin.package:
    update_cache: true
  when: ansible_os_family in ['Debian', 'RedHat']
  tags:
    - monitoring
    - install

- name: Install monitoring packages
  ansible.builtin.package:
    name: "{{ monitoring_packages[ansible_os_family] | default([]) }}"
    state: present
  when: monitoring_packages is defined
  tags:
    - monitoring
    - install

- name: Create monitoring directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ monitoring_user | default('root') }}"
    group: "{{ monitoring_group | default('root') }}"
    mode: '0755'
  loop: "{{ monitoring_directories | default([]) }}"
  tags:
    - monitoring
    - install
