- name: Check if Prometheus Node Exporter is already installed
  ansible.builtin.stat:
    path: /usr/local/bin/node_exporter
  register: node_exporter_installed
  tags:
    - monitoring
- name: Create prometheus user
  ansible.builtin.user:
    name: prometheus
    system: true
    shell: /bin/false
    home: /var/lib/prometheus
    create_home: false
    comment: Prometheus monitoring user
  when: not node_exporter_installed.stat.exists
  tags:
    - monitoring
- name: Create prometheus directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  loop:
    - /var/lib/prometheus
    - /etc/prometheus
  when: not node_exporter_installed.stat.exists
  tags:
    - monitoring
- name: Download Prometheus Node Exporter
  ansible.builtin.get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.6.1/node_exporter-1.6.1.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz
    mode: '0644'
  when: not node_exporter_installed.stat.exists
  tags:
    - monitoring
- name: Extract Node Exporter
  ansible.builtin.unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /tmp
    remote_src: true
  when: not node_exporter_installed.stat.exists
  tags:
    - monitoring
- name: Copy Node Exporter binary
  ansible.builtin.copy:
    src: /tmp/node_exporter-1.6.1.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    owner: prometheus
    group: prometheus
    mode: '0755'
    remote_src: true
  when: not node_exporter_installed.stat.exists
  tags:
    - monitoring
- name: Create Node Exporter systemd service
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload systemd
    - restart node_exporter
  tags:
    - monitoring
- name: Create PowerDNS custom metrics script
  ansible.builtin.template:
    src: powerdns_exporter.sh.j2
    dest: /usr/local/bin/powerdns_exporter.sh
    owner: prometheus
    group: prometheus
    mode: '0755'
  tags:
    - monitoring
- name: Create PowerDNS metrics collection service
  ansible.builtin.template:
    src: powerdns_metrics.service.j2
    dest: /etc/systemd/system/powerdns_metrics.service
    owner: root
    group: root
    mode: '0644'
  notify: reload systemd
  tags:
    - monitoring
- name: Create PowerDNS metrics collection timer
  ansible.builtin.template:
    src: powerdns_metrics.timer.j2
    dest: /etc/systemd/system/powerdns_metrics.timer
    owner: root
    group: root
    mode: '0644'
  notify: reload systemd
  tags:
    - monitoring
- name: Enable and start Node Exporter
  ansible.builtin.systemd:
    name: node_exporter
    enabled: true
    state: started
    daemon_reload: true
  tags:
    - monitoring
- name: Enable and start PowerDNS metrics collection
  ansible.builtin.systemd:
    name: powerdns_metrics.timer
    enabled: true
    state: started
    daemon_reload: true
  tags:
    - monitoring
- name: Configure firewall for Prometheus (if UFW is active)
  community.general.ufw:
    rule: allow
    port: '{{ monitoring_config.prometheus_port }}'
    proto: tcp
    comment: Prometheus Node Exporter
  when: ansible_os_family == "Debian"
  failed_when: false
  tags:
    - monitoring
- name: Configure firewall for Prometheus (if firewalld is active)
  ansible.posix.firewalld:
    port: '{{ monitoring_config.prometheus_port }}/tcp'
    permanent: true
    state: enabled
    immediate: true
  when: ansible_os_family == "RedHat"
  failed_when: false
  tags:
    - monitoring
- name: Clean up downloaded files
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  loop:
    - /tmp/node_exporter.tar.gz
    - /tmp/node_exporter-1.6.1.linux-amd64
  when: not node_exporter_installed.stat.exists
  tags:
    - monitoring
- name: Verify Node Exporter is running
  ansible.builtin.uri:
    url: http://localhost:{{ monitoring_config.prometheus_port }}/metrics
    method: GET
    status_code: 200
  register: node_exporter_check
  retries: 3
  delay: 5
  tags:
    - monitoring
- name: Display Prometheus setup status
  ansible.builtin.debug:
    msg:
      - Prometheus Node Exporter installed successfully
      - 'Metrics endpoint: http://{{ ansible_default_ipv4.address }}:{{ monitoring_config.prometheus_port }}/metrics'
      - 'PowerDNS custom metrics: Enabled'
  when: node_exporter_check.status == 200
  tags:
    - monitoring
