---
# Keepalived handlers

- name: Restart keepalived
  ansible.builtin.systemd:
    name: keepalived
    state: restarted
    enabled: true
    daemon_reload: true

- name: Reload keepalived
  ansible.builtin.systemd:
    name: keepalived
    state: reloaded

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart keepalived-check
  ansible.builtin.systemd:
    name: keepalived-check.service
    state: restarted
    enabled: true
    daemon_reload: true

- name: Start keepalived-check-timer
  ansible.builtin.systemd:
    name: keepalived-check.timer
    state: started
    enabled: true
    daemon_reload: true

- name: Reload firewall
  ansible.builtin.systemd:
    name: ufw
    state: reloaded
  when: ansible_os_family == "Debian"

