---
# Keepalived handlers

- name: restart keepalived
  ansible.builtin.systemd:
    name: keepalived
    state: restarted
    enabled: yes
    daemon_reload: true

- name: reload keepalived
  ansible.builtin.systemd:
    name: keepalived
    state: reloaded

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart keepalived-check
  ansible.builtin.systemd:
    name: keepalived-check.service
    state: restarted
    enabled: yes
    daemon_reload: true

- name: start keepalived-check-timer
  ansible.builtin.systemd:
    name: keepalived-check.timer
    state: started
    enabled: yes
    daemon_reload: true

- name: reload firewall
  ansible.builtin.systemd:
    name: ufw
    state: reloaded
  when: ansible_os_family == "Debian"
