---
# Common handlers for PowerDNS setup

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart powerdns-health-check.timer
  ansible.builtin.systemd:
    name: powerdns-health-check.timer
    state: restarted
    enabled: true
    daemon_reload: true
  become: true
  when: not ansible_check_mode
  failed_when: false
  changed_when: false

- name: Restart powerdns-health-check.service
  ansible.builtin.systemd:
    name: powerdns-health-check.service
    state: restarted
    daemon_reload: true
  become: true
  when: not ansible_check_mode
  failed_when: false
  changed_when: false

- name: Start powerdns-health-check.timer
  ansible.builtin.systemd:
    name: powerdns-health-check.timer
    state: started
    enabled: true
    daemon_reload: true
  become: true
  when:
    - monitoring_config.enabled | default(true)
    - not ansible_check_mode
  failed_when: false
  changed_when: false
