---
# Common handlers for PowerDNS setup

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: yes

- name: restart powerdns-health-check.timer
  ansible.builtin.systemd:
    name: powerdns-health-check.timer
    state: restarted
    enabled: yes
    daemon_reload: true
  become: yes
  when: not ansible_check_mode
  ignore_errors: yes

- name: restart powerdns-health-check.service
  ansible.builtin.systemd:
    name: powerdns-health-check.service
    state: restarted
    daemon_reload: true
  become: yes
  when: not ansible_check_mode
  ignore_errors: yes

- name: start powerdns-health-check.timer
  ansible.builtin.systemd:
    name: powerdns-health-check.timer
    state: started
    enabled: yes
    daemon_reload: true
  become: yes
  when: 
    - monitoring_config.enabled | default(true)
    - not ansible_check_mode
  ignore_errors: yes
