---
# PowerDNS Recursor handlers

- name: restart recursor
  ansible.builtin.systemd:
    name: "{{ recursor_service_name }}"
    state: restarted
    enabled: yes
    daemon_reload: true

- name: reload recursor
  ansible.builtin.systemd:
    name: "{{ recursor_service_name }}"
    state: reloaded

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: validate recursor config
  ansible.builtin.command: pdns_recursor --config-check
  register: recursor_config_check
  failed_when: recursor_config_check.rc != 0
  changed_when: false

- name: reload firewall
  ansible.builtin.systemd:
    name: ufw
    state: reloaded
  when: ansible_os_family == "Debian"
