---
# HAProxy handlers

- name: Restart haproxy
  ansible.builtin.systemd:
    name: haproxy
    state: restarted
    enabled: true
    daemon_reload: true

- name: Reload haproxy
  ansible.builtin.systemd:
    name: haproxy
    state: reloaded

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Validate haproxy config
  ansible.builtin.command: haproxy -c -f /etc/haproxy/haproxy.cfg
  register: haproxy_config_check
  failed_when: haproxy_config_check.rc != 0
  changed_when: false
