---
# HAProxy handlers

- name: restart haproxy
  ansible.builtin.systemd:
    name: haproxy
    state: restarted
    enabled: yes
    daemon_reload: true

- name: reload haproxy
  ansible.builtin.systemd:
    name: haproxy
    state: reloaded

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: validate haproxy config
  ansible.builtin.command: haproxy -c -f /etc/haproxy/haproxy.cfg
  register: haproxy_config_check
  failed_when: haproxy_config_check.rc != 0
  changed_when: false
