---
# handlers for galera role

- name: Restart MySQL
  ansible.builtin.service:
    name: mysql
    state: restarted
  listen: restart mysql

- name: Restart Galera health check
  ansible.builtin.service:
    name: galera-health-check
    state: restarted
  listen: restart galera-health-check

- name: Start Galera health check timer
  ansible.builtin.service:
    name: galera-health-check.timer
    state: started
    enabled: true
  listen: start galera-health-check-timer

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: reload systemd
