---
# Clean Install Handlers

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: reload systemd

- name: Clean package cache
  ansible.builtin.package:
    update_cache: true
  listen: clean package cache
