---
# Handlers for MySQL role

- name: restart mysql
  ansible.builtin.service:
    name: "{{ mysql_service_name }}"
    state: restarted
    enabled: yes
    daemon_reload: yes
  listen: restart mysql

- name: reload mysql
  ansible.builtin.service:
    name: "{{ mysql_service_name }}"
    state: reloaded
  listen: reload mysql

- name: start mysql
  ansible.builtin.service:
    name: "{{ mysql_service_name }}"
    state: started
    enabled: yes
  listen: start mysql

- name: stop mysql
  ansible.builtin.service:
    name: "{{ mysql_service_name }}"
    state: stopped
  listen: stop mysql

- name: reload systemd
  systemd:
    daemon_reload: yes
  listen: reload systemd
