---
# MySQL Role Handlers

- name: Restart mysql
  ansible.builtin.service:
    name: "{{ mysql_service_name }}"
    state: restarted
    enabled: true
    daemon_reload: true
  listen: restart mysql

- name: Reload mysql
  ansible.builtin.service:
    name: "{{ mysql_service_name }}"
    state: reloaded
  listen: reload mysql

- name: Start mysql
  ansible.builtin.service:
    name: "{{ mysql_service_name }}"
    state: started
    enabled: true
  listen: start mysql

- name: Stop mysql
  ansible.builtin.service:
    name: "{{ mysql_service_name }}"
    state: stopped
  listen: stop mysql

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: reload systemd
