---
# MySQL Role Handlers

- name: restart mysql
  systemd:
    name: "{{ mysql_service_name }}"
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: reload mysql
  systemd:
    name: "{{ mysql_service_name }}"
    state: reloaded

- name: start mysql
  systemd:
    name: "{{ mysql_service_name }}"
    state: started
    enabled: yes

- name: stop mysql
  systemd:
    name: "{{ mysql_service_name }}"
    state: stopped

- name: reload systemd
  systemd:
    daemon_reload: yes
