---
# Installation tasks for recursor

- name: Update package cache
  ansible.builtin.package:
    update_cache: true
  when: ansible_os_family in ['Debian', 'RedHat']
  tags:
    - recursor
    - install

- name: Install recursor packages
  ansible.builtin.package:
    name: "{{ recursor_packages[ansible_os_family] | default([]) }}"
    state: present
  when: recursor_packages is defined
  tags:
    - recursor
    - install

- name: Create recursor directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ recursor_user | default('root') }}"
    group: "{{ recursor_group | default('root') }}"
    mode: '0755'
  loop: "{{ recursor_directories | default([]) }}"
  tags:
    - recursor
    - install
