---
# Handlers for self_healing role

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  listen: "reload systemd"

- name: restart powerdns-watchdog
  ansible.builtin.systemd:
    name: powerdns-watchdog.service
    state: restarted
    enabled: yes
    daemon_reload: yes
  listen: "restart powerdns-watchdog"

- name: start powerdns-watchdog-timer
  ansible.builtin.systemd:
    name: powerdns-watchdog.timer
    state: started
    enabled: yes
    daemon_reload: yes
  listen: "start powerdns-watchdog-timer"

- name: restart mysql-watchdog
  ansible.builtin.systemd:
    name: mysql-watchdog.service
    state: restarted
    enabled: yes
    daemon_reload: yes
  listen: "restart mysql-watchdog"

- name: start mysql-watchdog-timer
  ansible.builtin.systemd:
    name: mysql-watchdog.timer
    state: started
    enabled: yes
    daemon_reload: yes
  listen: "start mysql-watchdog-timer"
