---
# Installation tasks for zones_as_code

- name: Update package cache
  ansible.builtin.package:
    update_cache: true
  when: ansible_os_family in ['Debian', 'RedHat']
  tags:
    - zones_as_code
    - install

- name: Install zones_as_code packages
  ansible.builtin.package:
    name: "{{ zones_as_code_packages[ansible_os_family] | default([]) }}"
    state: present
  when: zones_as_code_packages is defined
  tags:
    - zones_as_code
    - install

- name: Create zones_as_code directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ zones_as_code_user | default('root') }}"
    group: "{{ zones_as_code_group | default('root') }}"
    mode: '0755'
  loop: "{{ zones_as_code_directories | default([]) }}"
  tags:
    - zones_as_code
    - install
