---
name: Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint yamllint

      - name: Lint YAML files
        run: yamllint .

      - name: Lint Ansible files
        run: ansible-lint

  molecule-test:
    name: Molecule Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario: [default, security, ha_cluster]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install molecule[docker] ansible pytest

      - name: Run Molecule test
        run: molecule test -s ${{ matrix.scenario }}
        env:
          MOLECULE_NO_LOG: false

  syntax-check:
    name: Syntax Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Check playbook syntax
        run: |
          ansible-playbook --syntax-check powerdns-operational-playbook.yml
          ansible-playbook --syntax-check powerdns-playbook.yml

      - name: Check inventory
        run: |
          ansible-inventory -i inventory/hosts.yml --list > /dev/null

  collection-build:
    name: Collection Build Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Build collection
        run: |
          ansible-galaxy collection build

      - name: Install collection
        run: |
          ansible-galaxy collection install community-powerdns_ops-*.tar.gz

      - name: Test collection import
        run: |
          ansible-doc community.powerdns_ops.powerdns || true
